{% set name = "py2cfg" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/py2cfg-{{ version }}.tar.gz
  sha256: 1be0d8da89ffb7f91b99e4f62cd7de2c1dffeeef93b45e5c7d1f9e667458b413
  patches:
    - pyproject.patch

build:
  entry_points:
    - py2cfg = py2cfg._runner:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - poetry >=0.12.3
    - poetry-core
    - pip
  run:
    - python >=3.7
    - astor >=0.8.0,<0.9.0
    - pudb >=2022.0.0,<2023.0.0
    - websocket-server >=0.4
    - python-graphviz >=0.1
    - flask >=1.0.0,<2.0.0
    - requests >=2.0.0,<3.0.0
    - packaging
    - __unix

test:
  imports:
    - py2cfg
  commands:
    - pip check
    - py2cfg --help
  requires:
    - pip

about:
  home: https://gitlab.com/classroomcode/py2cfg
  summary: Converts python source code to colorful Control Flow Graphs (CFGs).
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
